name: Shareable APK Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Build Android Package
        uses: ssthouse/pwa-to-apk-action@v1
        with:
          title: "Kitsune Handheld Suite"
          url: "https://10010011011.github.io/Kitsune-calc/"
          icon_url: "https://10010011011.github.io/Kitsune-calc/imresizer-file_00000000e1bc7207bd9f7023a8dee8f0%20(1).png"

      - name: Upload Finished APK
        uses: actions/upload-artifact@v3
        with:
          name: Kitsune-Shareable-APK
          path: ./*.apk
